language: node_js

node_js:
  - "7"

os:
    - linux

dist: trusty
  
git:
  depth: false
  submodules: false

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}

script:
  - docker login -u $DOCKER_NAME -p $DOCKER_PASSWORD
  - export SASHIMI=$DOCKER_NAME/$SASHIMI_REPO
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile-sashimi -t $SASHIMI:$COMMIT .
  - docker tag $SASHIMI:$COMMIT $SASHIMI:$TAG
  - docker tag $SASHIMI:$COMMIT $SASHIMI:travis-$TRAVIS_BUILD_NUMBER
  - docker push $SASHIMI
  - export TRITTICO=$DOCKER_NAME/$TRITTICO_REPO
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile-trittico -t $TRITTICO:$COMMIT .
  - docker tag $TRITTICO:$COMMIT $TRITTICO:$TAG
  - docker tag $TRITTICO:$COMMIT $TRITTICO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $TRITTICO

branches:
  only:
    master

notifications:
    email:
      on_success: always
      on_failure: always
